// Code generated by goctl. DO NOT EDIT.
// Source: system.proto

package server

import (
	"context"

	"chatops-server/internal/system/rpc/internal/logic"
	"chatops-server/internal/system/rpc/internal/svc"
	"chatops-server/internal/system/rpc/system"
)

type SystemServer struct {
	svcCtx *svc.ServiceContext
	system.UnimplementedSystemServer
}

func NewSystemServer(svcCtx *svc.ServiceContext) *SystemServer {
	return &SystemServer{
		svcCtx: svcCtx,
	}
}

func (s *SystemServer) SystemDetailInfo(ctx context.Context, in *system.SystemDetailInfoRequest) (*system.SystemDetailInfoResponse, error) {
	l := logic.NewSystemDetailInfoLogic(ctx, s.svcCtx)
	return l.SystemDetailInfo(in)
}

func (s *SystemServer) UpdateSystemInfo(ctx context.Context, in *system.UpdateSystemInfoRequest) (*system.UpdateSystemInfoResponse, error) {
	l := logic.NewUpdateSystemInfoLogic(ctx, s.svcCtx)
	return l.UpdateSystemInfo(in)
}

func (s *SystemServer) SecretDetailInfo(ctx context.Context, in *system.SecretDetailInfoRequest) (*system.SecretDetailInfoResponse, error) {
	l := logic.NewSecretDetailInfoLogic(ctx, s.svcCtx)
	return l.SecretDetailInfo(in)
}

func (s *SystemServer) UpdateSecretInfo(ctx context.Context, in *system.UpdateSecretInfoRequest) (*system.UpdateSecretInfoResponse, error) {
	l := logic.NewUpdateSecretInfoLogic(ctx, s.svcCtx)
	return l.UpdateSecretInfo(in)
}
