// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: system.proto

package system

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	System_SystemDetailInfo_FullMethodName = "/system.System/systemDetailInfo"
	System_UpdateSystemInfo_FullMethodName = "/system.System/updateSystemInfo"
	System_SecretDetailInfo_FullMethodName = "/system.System/secretDetailInfo"
	System_UpdateSecretInfo_FullMethodName = "/system.System/updateSecretInfo"
)

// SystemClient is the client API for System service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemClient interface {
	SystemDetailInfo(ctx context.Context, in *SystemDetailInfoRequest, opts ...grpc.CallOption) (*SystemDetailInfoResponse, error)
	UpdateSystemInfo(ctx context.Context, in *UpdateSystemInfoRequest, opts ...grpc.CallOption) (*UpdateSystemInfoResponse, error)
	SecretDetailInfo(ctx context.Context, in *SecretDetailInfoRequest, opts ...grpc.CallOption) (*SecretDetailInfoResponse, error)
	UpdateSecretInfo(ctx context.Context, in *UpdateSecretInfoRequest, opts ...grpc.CallOption) (*UpdateSecretInfoResponse, error)
}

type systemClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemClient(cc grpc.ClientConnInterface) SystemClient {
	return &systemClient{cc}
}

func (c *systemClient) SystemDetailInfo(ctx context.Context, in *SystemDetailInfoRequest, opts ...grpc.CallOption) (*SystemDetailInfoResponse, error) {
	out := new(SystemDetailInfoResponse)
	err := c.cc.Invoke(ctx, System_SystemDetailInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) UpdateSystemInfo(ctx context.Context, in *UpdateSystemInfoRequest, opts ...grpc.CallOption) (*UpdateSystemInfoResponse, error) {
	out := new(UpdateSystemInfoResponse)
	err := c.cc.Invoke(ctx, System_UpdateSystemInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) SecretDetailInfo(ctx context.Context, in *SecretDetailInfoRequest, opts ...grpc.CallOption) (*SecretDetailInfoResponse, error) {
	out := new(SecretDetailInfoResponse)
	err := c.cc.Invoke(ctx, System_SecretDetailInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemClient) UpdateSecretInfo(ctx context.Context, in *UpdateSecretInfoRequest, opts ...grpc.CallOption) (*UpdateSecretInfoResponse, error) {
	out := new(UpdateSecretInfoResponse)
	err := c.cc.Invoke(ctx, System_UpdateSecretInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServer is the server API for System service.
// All implementations must embed UnimplementedSystemServer
// for forward compatibility
type SystemServer interface {
	SystemDetailInfo(context.Context, *SystemDetailInfoRequest) (*SystemDetailInfoResponse, error)
	UpdateSystemInfo(context.Context, *UpdateSystemInfoRequest) (*UpdateSystemInfoResponse, error)
	SecretDetailInfo(context.Context, *SecretDetailInfoRequest) (*SecretDetailInfoResponse, error)
	UpdateSecretInfo(context.Context, *UpdateSecretInfoRequest) (*UpdateSecretInfoResponse, error)
	mustEmbedUnimplementedSystemServer()
}

// UnimplementedSystemServer must be embedded to have forward compatible implementations.
type UnimplementedSystemServer struct {
}

func (UnimplementedSystemServer) SystemDetailInfo(context.Context, *SystemDetailInfoRequest) (*SystemDetailInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SystemDetailInfo not implemented")
}
func (UnimplementedSystemServer) UpdateSystemInfo(context.Context, *UpdateSystemInfoRequest) (*UpdateSystemInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSystemInfo not implemented")
}
func (UnimplementedSystemServer) SecretDetailInfo(context.Context, *SecretDetailInfoRequest) (*SecretDetailInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SecretDetailInfo not implemented")
}
func (UnimplementedSystemServer) UpdateSecretInfo(context.Context, *UpdateSecretInfoRequest) (*UpdateSecretInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSecretInfo not implemented")
}
func (UnimplementedSystemServer) mustEmbedUnimplementedSystemServer() {}

// UnsafeSystemServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServer will
// result in compilation errors.
type UnsafeSystemServer interface {
	mustEmbedUnimplementedSystemServer()
}

func RegisterSystemServer(s grpc.ServiceRegistrar, srv SystemServer) {
	s.RegisterService(&System_ServiceDesc, srv)
}

func _System_SystemDetailInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemDetailInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SystemDetailInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: System_SystemDetailInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SystemDetailInfo(ctx, req.(*SystemDetailInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_UpdateSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSystemInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).UpdateSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: System_UpdateSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).UpdateSystemInfo(ctx, req.(*UpdateSystemInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_SecretDetailInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecretDetailInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).SecretDetailInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: System_SecretDetailInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).SecretDetailInfo(ctx, req.(*SecretDetailInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _System_UpdateSecretInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecretInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServer).UpdateSecretInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: System_UpdateSecretInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServer).UpdateSecretInfo(ctx, req.(*UpdateSecretInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// System_ServiceDesc is the grpc.ServiceDesc for System service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var System_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "system.System",
	HandlerType: (*SystemServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "systemDetailInfo",
			Handler:    _System_SystemDetailInfo_Handler,
		},
		{
			MethodName: "updateSystemInfo",
			Handler:    _System_UpdateSystemInfo_Handler,
		},
		{
			MethodName: "secretDetailInfo",
			Handler:    _System_SecretDetailInfo_Handler,
		},
		{
			MethodName: "updateSecretInfo",
			Handler:    _System_UpdateSecretInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "system.proto",
}
